// export { default as Layout } from "./Layout/Layout.js"
export { Layout } from "./Layout/Layout"
export { Main } from "./RootPage/Main"
export { default as Category } from "./RootPage/Category"
export { ImageGroup } from "./SlugPage/ImageGroup"
export { Pagination } from "./SlugPage/Pagination"
export { Menu } from "./Modal/Menu"
export { EnlargeImg } from "./Modal/EnlargeImg"
